import uuid
from dataclasses import dataclass, field, replace
from datetime import UTC, datetime

USER_ID_PREFIX = "usr_"
USER_ID_LENGTH = 12

#: Fields a caller may change. Kept in one place so a new field is added once.
MUTABLE_FIELDS = (
    "name",
    "phone",
    "language",
    "timezone",
    "preferred_agent",
    "preferred_provider",
    "metadata",
)


def new_user_id() -> str:
    """Return a fresh platform user id, for example `usr_3f8a1c9d2b04`.

    The id is generated by the platform and never derived from the identifier of
    a messenger, so the same profile can later be reached from Telegram, REST,
    Discord or a web interface.
    """
    return f"{USER_ID_PREFIX}{uuid.uuid4().hex[:USER_ID_LENGTH]}"


def now() -> datetime:
    """Return the current moment in UTC."""
    return datetime.now(UTC)


@dataclass(frozen=True)
class UserProfile:
    """Who a user is, as opposed to what stack they run on.

    A profile carries identity and preferences; the runtime stack lives in the
    workspace. The profile is immutable, so a change produces a new value and a
    reader can never observe a half-updated profile.
    """

    user_id: str
    telegram_id: str = ""
    name: str = ""
    phone: str = ""
    language: str = "ru"
    timezone: str = "UTC"
    created_at: datetime = field(default_factory=now)
    updated_at: datetime = field(default_factory=now)
    preferred_agent: str = ""
    preferred_provider: str = ""
    metadata: dict[str, str] = field(default_factory=dict)

    def with_changes(self, **changes: object) -> "UserProfile":
        """Return a copy with the given fields replaced and `updated_at` bumped.

        Args:
            **changes: Any of `MUTABLE_FIELDS`. `None` values are ignored, so a
                partial update leaves the rest untouched.

        Raises:
            ValueError: If a field is not one a caller may change.
        """
        applied: dict[str, object] = {}

        for name, value in changes.items():
            if value is None:
                continue
            if name not in MUTABLE_FIELDS:
                raise ValueError(
                    f"Unknown profile field: '{name}'. "
                    f"Known fields: {', '.join(MUTABLE_FIELDS)}."
                )
            applied[name] = value

        return replace(self, updated_at=now(), **applied)

    def is_complete(self) -> bool:
        """Whether the profile has been through the first-run questions."""
        return bool(self.name)

    def as_dict(self) -> dict[str, str]:
        """Return the profile as plain data for the bot and for reporting."""
        return {
            "user_id": self.user_id,
            "telegram_id": self.telegram_id,
            "name": self.name,
            "phone": self.phone,
            "language": self.language,
            "timezone": self.timezone,
            "created_at": self.created_at.isoformat(timespec="seconds"),
            "updated_at": self.updated_at.isoformat(timespec="seconds"),
            "preferred_agent": self.preferred_agent,
            "preferred_provider": self.preferred_provider,
        }
